[1.20] Create Chinese language file (zh_cn.json)
Pandarix/Beautify pull request #24
Opened 2024-01-02 12:10 UTC by NumberSir

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.dark_oak_blinds": "深色百叶窗",
```suggestion
  "block.beautify.dark_oak_blinds": "深色橡木百叶窗",
```

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "sounds.beautify.bookstack_break": "书堆破损",
Are these subtitles?

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "trellis.description2": "手拿植物右键可以插入",
```suggestion
  "trellis.description2": "手持植物右击以插入",
```

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "blinds.description1": "右键开关选中的和左右相连的百叶窗",
```suggestion
  "blinds.description1": "右击方块以开关选中的和周围的百叶窗",
```

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "candelabra.description2": "空手右键熄灭",
```suggestion
  "candelabra.description2": "空手右击熄灭",
```

2024-02-05 04:58 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "candelabra.description2": "空手右键熄灭",
Please change ALL "左/右键" in to "左/右击"
Because "左/右键" is noun.

2024-02-05 05:08 UTC, nageih requested changes

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.birch_picture_frame": "桦树相框",
```suggestion
  "block.beautify.birch_picture_frame": "白桦木相框",
```

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.spruce_picture_frame": "云杉相框",
```suggestion
  "block.beautify.spruce_picture_frame": "云杉木相框",
```

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.jungle_picture_frame": "丛林相框",
```suggestion
  "block.beautify.jungle_picture_frame": "丛林木相框",
```

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.acacia_picture_frame": "合金欢木相框",
```suggestion
  "block.beautify.acacia_picture_frame": "金合欢木相框",
```

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.spruce_picture_frame": "云杉相框",
Same for the rest

2024-02-05 05:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "block.beautify.spruce_picture_frame": "云杉相框",
Same for the rest

2024-11-13 12:36 UTC, NumberSir commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "sounds.beautify.bookstack_break": "书堆破损",
是，右下角显示的声音字幕

2024-11-13 14:08 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "sounds.beautify.bookstack_break": "书堆破损",
在`书堆`和`破碎`之间需要有全角冒号，原版的格式

2024-11-13 14:17 UTC, nageih commented on src/main/resources/assets/beautify/lang/zh_cn.json
> +  "sounds.beautify.bookstack_break": "书堆破损",
在`书堆`和`破碎`之间需要有全角冒号，是原版的格式

2025-02-17 21:50 UTC, NumberSir commented
@Pandarix Hi all the conflict parts have been resolved and we'll be appreciated if you could merge the pull request 😊

2026-06-09 02:11 UTC, closed without merging